name: Publish Docker Image for ZSA Voyager Keymap

on:
  push:
    paths:
      - 'Dockerfile'
      - '.github/workflows/build-and-publish-docker-image.yml'

jobs:
  publish-zsa-voyager-keymap-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the zsa-voyager-keymap Docker image
      run: |
        curl -sL https://github.com/shinsenter/docker-squash/raw/main/docker-squash.sh -o ./docker-squash.sh
        chmod +x ./docker-squash.sh
        docker build . --tag ghcr.io/ericreeves/zsa-voyager-keymap:build
        docker run ghcr.io/ericreeves/zsa-voyager-keymap:build
        ./docker-squash.sh ghcr.io/ericreeves/zsa-voyager-keymap:build ghcr.io/ericreeves/zsa-voyager-keymap:latest
        docker push ghcr.io/ericreeves/zsa-voyager-keymap:latest

